version: '3.8'

services:
  web:
    build: .
    ports:
      - "9080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=classified_ads
      - MYSQL_USER=classified_user
      - MYSQL_PASSWORD=classified_pass
      - MYSQL_ROOT_PASSWORD=classified_root
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: classified_ads
      MYSQL_USER: classified_user
      MYSQL_PASSWORD: classified_pass
      MYSQL_ROOT_PASSWORD: classified_root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "9081:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  db_data: